### ISSUE TITLE
"Natural" distribution calculation

### ISSUE THREAD

**Issue by tapaswini-kodavanti** [y0mingzhang/diffuse-distributions#1]
Hello! I was hoping to get more clarification on how the Natural Distributions were calculated for the two tasks (RNG and Baby Names) under Section 4. Specifically, I'm curious about how an entropy value of 6.43 and a coverage-1000 value of 714 were calculated for the Baby Names task (info in Table 4).

**Comment by y0mingzhang** [comment]
For RNG: the natural distribution is defined as a uniform distribution over the numbers 1 to 10, and the entropy (in nats) is $\ln(10) = 2.30$. Coverage-1000 is the number of unique items in 1000 generations, so this is just 10.

For Baby Names: we took a random sample of 1000 names with probabilities proportional to their popularity among US newborns in 2022. Entropy is computed as the empirical entropy of this distribution (6.43), and Coverage-1000 is the number of unique names in the sample (714).

If you need the original sample of names, I can send a copy to you.

**Comment by tapaswini-kodavanti** [comment]
Yes, that would be great! My email is tapaswini.kodavanti@gmail.com.
